import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import Signup from '../components/signupDialog'
import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';
import Link from '@mui/material/Link';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import InputAdornment from '@mui/material/InputAdornment';
import Visibility from '@mui/icons-material/Visibility';
import VisibilityOff from '@mui/icons-material/VisibilityOff';
import { useState } from 'react';

//This is the landing page of the website. Can be the login page

export default function Home() {
	const accounts = {user: "user", pass: "pass"};
  
	const [user, setUser] = useState({
		value: '',
		error: false,
		alert: false,
	});
  
	const [pass, setPass] = useState({
	value: '',
	error: false,
	alert: false,
	showPass: false,
	});
  
	const [signup, setSignup] = useState(false);
  
	const handleSubmit = (event) => {
		setUser({...user, error: false, alert: false});
		setPass({...pass, error: false, alert: false});
	
		const error = false;
		if(!user.value) {
			setUser({...user, error: true});
			event.preventDefault();
		} else if(user.value !== accounts.user) {
			setUser({...user, error: true, alert: true});
			event.preventDefault();
		} else {
			if(pass.value && pass.value !== accounts.pass) {
				setPass({...pass, error: true, alert: true});
				event.preventDefault();
			}
		}
	
		if(!pass.value) {
			setPass({...pass, error: true});
			event.preventDefault();
		}
	};
  
	const handleOpen = () => {
		setSignup(true);
	}
  
	const handleClose = () => {
		setSignup(false);
	}
  
	const handleShowPass = () => {
		setPass({...pass, showPass: !pass.showPass});
	};
  
	return (
		<div className={styles.container}>
			<Head>
				<title>Sign in</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Typography component="h1" variant="h5">
					Sign in
				</Typography>
				<Box component="form" validate sx={{ mt: 1 }}>
					<TextField
						onChange={(event) => setUser({...user, value: event.target.value})}
						error={user.error}
						margin="normal"
						required
						fullWidth
						id="username"
						label={user.alert? "Username does not exist" : "Username"}
						name="username"
						autoComplete="username"
						autoFocus
					/>
					<TextField
						onChange={(event) => setPass({...pass, value: event.target.value})}
						error={pass.error}
						margin="normal"
						required
						fullWidth
						name="password"
						label={pass.alert? "Incorrect password" : "Password"}
						id="password"
						autoComplete="current-password"
						type={pass.showPass ? "text" : "password"}
						InputProps={{
							endAdornment: (
								<InputAdornment position="end">
									<IconButton
										aria-label="toggle password visibility"
										onClick={handleShowPass}
										edge="end"
									>
										{pass.showPass ? <Visibility /> : <VisibilityOff />}
									</IconButton>
								</InputAdornment>
							),
						}}
					/>
					<Button
						onClick={handleSubmit}
						href="/resources"
						type="submit"
						fullWidth
						variant="contained"
						sx={{ mt: 3, mb: 2 }}
					>
						Sign In
					</Button>
					<Button variant="text" onClick={handleOpen}>
						{"Don't have an account? Sign Up"}
					</Button>
					<Signup open={signup} onClose={handleClose} />
				</Box>
			</main>
		</div>
	);
}
